# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cassandra:
        image: cassandra
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
    steps:
    - uses: actions/checkout@v2
    - run: docker ps
    - run: docker cp misc/create_test_schema.cql ${{ job.services.cassandra.id }}:/
    - run: docker exec ${{ job.services.cassandra.id }} cqlsh --debug localhost 9042 -f /create_test_schema.cql
    - run: docker exec ${{ job.services.cassandra.id }} cqlsh --debug localhost 9042 --execute="describe keyspaces;"
    - run: python test_minicql.py
